### ISSUE TITLE
Publish artifact on build success

### ISSUE THREAD

**Issue by RMuskovets** [l1ttleO/Boyfriend#1]
It'd be good to have the Actions workflow publish a .JAR of the bot if build succeeded, with name like this: `<BRANCH>-<COMMIT SHORT HASH>`.

**Comment by RMuskovets** [comment]
<@!504343489664909322>

**Comment by l1ttleO** [comment]
why you need the .JAR of the original? some bot features are hard coded and without changing the source you can't use it in full. i published source just for others to find bugs, suggest and PR features, etc.
also discord pings don't work lulw
